import React from "react";

const DesignSystem=()=>{
    return(
        <div>
            <h1>DesignSysTem</h1>
            <p>So, I have a sticky header which should appear once the user has scrolled a X amount of pixels (420px in this example). Once it hits 420px, it shows an animation sliding the header down. When I scroll the screen back up, however, the sticky header just "disappears" in a very cold way. The idea is that it would also "slide" up and disappear in a reverse way as it appeared. An example of what I want to achieve -> https://www.pretto.fr/ I want exactly this, for the header to slide when it comes down but when I scroll back up, for it scroll up disappearing.</p>
            <p>So, I have a sticky header which should appear once the user has scrolled a X amount of pixels (420px in this example). Once it hits 420px, it shows an animation sliding the header down. When I scroll the screen back up, however, the sticky header just "disappears" in a very cold way. The idea is that it would also "slide" up and disappear in a reverse way as it appeared. An example of what I want to achieve -> https://www.pretto.fr/ I want exactly this, for the header to slide when it comes down but when I scroll back up, for it scroll up disappearing.</p>
            <p>So, I have a sticky header which should appear once the user has scrolled a X amount of pixels (420px in this example). Once it hits 420px, it shows an animation sliding the header down. When I scroll the screen back up, however, the sticky header just "disappears" in a very cold way. The idea is that it would also "slide" up and disappear in a reverse way as it appeared. An example of what I want to achieve -> https://www.pretto.fr/ I want exactly this, for the header to slide when it comes down but when I scroll back up, for it scroll up disappearing.</p>
            <p>So, I have a sticky header which should appear once the user has scrolled a X amount of pixels (420px in this example). Once it hits 420px, it shows an animation sliding the header down. When I scroll the screen back up, however, the sticky header just "disappears" in a very cold way. The idea is that it would also "slide" up and disappear in a reverse way as it appeared. An example of what I want to achieve -> https://www.pretto.fr/ I want exactly this, for the header to slide when it comes down but when I scroll back up, for it scroll up disappearing.</p>
            <p>So, I have a sticky header which should appear once the user has scrolled a X amount of pixels (420px in this example). Once it hits 420px, it shows an animation sliding the header down. When I scroll the screen back up, however, the sticky header just "disappears" in a very cold way. The idea is that it would also "slide" up and disappear in a reverse way as it appeared. An example of what I want to achieve -> https://www.pretto.fr/ I want exactly this, for the header to slide when it comes down but when I scroll back up, for it scroll up disappearing.</p>
            <p>So, I have a sticky header which should appear once the user has scrolled a X amount of pixels (420px in this example). Once it hits 420px, it shows an animation sliding the header down. When I scroll the screen back up, however, the sticky header just "disappears" in a very cold way. The idea is that it would also "slide" up and disappear in a reverse way as it appeared. An example of what I want to achieve -> https://www.pretto.fr/ I want exactly this, for the header to slide when it comes down but when I scroll back up, for it scroll up disappearing.</p>
            <p>So, I have a sticky header which should appear once the user has scrolled a X amount of pixels (420px in this example). Once it hits 420px, it shows an animation sliding the header down. When I scroll the screen back up, however, the sticky header just "disappears" in a very cold way. The idea is that it would also "slide" up and disappear in a reverse way as it appeared. An example of what I want to achieve -> https://www.pretto.fr/ I want exactly this, for the header to slide when it comes down but when I scroll back up, for it scroll up disappearing.</p>
            <p>So, I have a sticky header which should appear once the user has scrolled a X amount of pixels (420px in this example). Once it hits 420px, it shows an animation sliding the header down. When I scroll the screen back up, however, the sticky header just "disappears" in a very cold way. The idea is that it would also "slide" up and disappear in a reverse way as it appeared. An example of what I want to achieve -> https://www.pretto.fr/ I want exactly this, for the header to slide when it comes down but when I scroll back up, for it scroll up disappearing.</p>
            <p>So, I have a sticky header which should appear once the user has scrolled a X amount of pixels (420px in this example). Once it hits 420px, it shows an animation sliding the header down. When I scroll the screen back up, however, the sticky header just "disappears" in a very cold way. The idea is that it would also "slide" up and disappear in a reverse way as it appeared. An example of what I want to achieve -> https://www.pretto.fr/ I want exactly this, for the header to slide when it comes down but when I scroll back up, for it scroll up disappearing.</p>
            <p>So, I have a sticky header which should appear once the user has scrolled a X amount of pixels (420px in this example). Once it hits 420px, it shows an animation sliding the header down. When I scroll the screen back up, however, the sticky header just "disappears" in a very cold way. The idea is that it would also "slide" up and disappear in a reverse way as it appeared. An example of what I want to achieve -> https://www.pretto.fr/ I want exactly this, for the header to slide when it comes down but when I scroll back up, for it scroll up disappearing.</p>
        </div>
    )
}

export default DesignSystem